# Feature Engineering

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from titanic.features import transform

In [3]:
df = pd.read_pickle('../../data/interim/all.pkl.zip')

In [4]:
df.head()

                  Survived Pclass  \
      PassengerId
train 1              False  Lower
      2               True  Upper
      3               True  Lower
      4               True  Upper
      5              False  Lower

                                                                Name     Sex  \
      PassengerId
train 1                                      Braund, Mr. Owen Harris    male
      2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female
      3                                       Heikkinen, Miss. Laina  female
      4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
      5                                     Allen, Mr. William Henry    male

                    Age  SibSp  Parch            Ticket     Fare Cabin  \
      PassengerId
train 1            22.0      1      0         A/5 21171   7.2500   NaN
      2            38.0      1      0          PC 17599  71.2833   C85
      3            26.0      0      0  STON/O2. 3101282   7.9250   NaN
      4            35.0      1      0            113803  53.1000  C123
      5            35.0      0      0            373450   8.0500   NaN

                      Embarked
      PassengerId
train 1            Southampton
      2              Cherbourg
      3            Southampton
      4            Southampton
      5            Southampton

In [5]:
transform.engineer_features(df)

                   Survived       Age      Fare  has_cabin  Pclass_Middle  \
      PassengerId
train 1                 0.0 -0.595237 -0.502445        0.0              0
      2                 1.0  0.553225  0.786845        1.0              0
      3                 1.0 -0.308121 -0.488854        0.0              0
      4                 1.0  0.337889  0.420730        1.0              0
      5                 0.0  0.337889 -0.486337        0.0              0
...                     ...       ...       ...        ...            ...
test  1305              NaN -0.279410 -0.486337        0.0              0
      1306              NaN  0.625004  1.544246        1.0              0
      1307              NaN  0.589114 -0.502445        0.0              0
      1308              NaN -0.279410 -0.486337        0.0              0
      1309              NaN -1.625938 -0.198244        0.0              0

                   Pclass_Upper  Sex_male  SibSp_1  SibSp_2+  Parch_1+  ...  \
      PassengerId                                                       ...
train 1                       0         1        1         0         0  ...
      2                       1         0        1         0         0  ...
      3                       0         0        0         0         0  ...
      4                       1         0        1         0         0  ...
      5                       0         1        0         0         0  ...
...                         ...       ...      ...       ...       ...  ...
test  1305                    0         1        0         0         0  ...
      1306                    1         0        0         0         0  ...
      1307                    0         1        0         0         0  ...
      1308                    0         1        0         0         0  ...
      1309                    0         1        1         0         1  ...

                   Title_Miss  Title_Mr  Title_Mrs  Title_Other  \
      PassengerId
train 1                     0         1          0            0
      2                     0         0          1            0
      3                     1         0          0            0
      4                     0         0          1            0
      5                     0         1          0            0
...                       ...       ...        ...          ...
test  1305                  0         1          0            0
      1306                  0         0          0            1
      1307                  0         1          0            0
      1308                  0         1          0            0
      1309                  0         0          0            0

                   Relatives_1-3  Relatives_4+  AgeBin_7-14  AgeBin_15-25  \
      PassengerId
train 1                        1             0            0             1
      2                        1             0            0             0
      3                        0             0            0             0
      4                        1             0            0             0
      5                        0             0            0             0
...                          ...           ...          ...           ...
test  1305                     0             0            0             0
      1306                     0             0            0             0
      1307                     0             0            0             0
      1308                     0             0            0             0
      1309                     1             0            1             0

                   AgeBin_26-45  AgeBin_45+
      PassengerId
train 1                       0           0
      2                       1           0
      3                       1           0
      4                       1           0
      5                       1           0
...                         ...         ...
test  1305                    1           0
      1306                    1           0
      1307                    1           0
      1308                    1           0
      1309                    0           0

[1309 rows x 22 columns]